name: Prettier

on: [push, pull_request]

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Prettier 
              uses: creyD/prettier_action@v4.3
              with:
                  prettier_options: --write src/**/*.{js,jsx,ts,tsx}
                  commit_message: '🥰 chore(ci): Make the code pretty'