name: Bump Beta Version

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'Select version bump type: major, minor, patch'
        required: true
        default: 'patch'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set Git identity
        run: |
          git config --local user.email "toxic.dev09@gmail.com"
          git config --local user.name "Toxic Dev"

      - name: Version bump
        run: |
          # Get the current version
          current_version=$(node -p "require('./package.json').version")
          # Extract the prerelease identifier
          preid=$(echo $current_version | grep -o -E "[-]([a-zA-Z0-9]+)[.]" | grep -o -E "([a-zA-Z0-9]+)")
          # Bump the version with prerelease identifier retained
          npm version ${{ github.event.inputs.semver }} --preid=$preid -m "Bump version to %s"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}